env:
  name: "humanoidmaze-medium-navigate-v0"
  device: "cuda"

output:
  dir: "humanoidmaze_navigate/medium"

encoder:
  # Model Architecture
  z_dim: 32
  hidden_dim: 512
  
  # Training / Optimizer Parameters
  batch_size: 1024
  steps: 1000000
  lr: 0.0003
  weight_decay: 1e-4
  discount_factor: 0.99
  expectile: 0.95
  target_update_rate: 0.005
  
  # Logging & Saving
  log_every: 1000
  val_every: 1000
  save_every: 500000
